const skus = [
  {
    skuId: '11026426',
    sizeName: 'XX Small',
    colorName: 'COBALT BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026433',
    sizeName: 'X Small',
    colorName: 'COBALT BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026440',
    sizeName: 'Small',
    colorName: 'COBALT BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026457',
    sizeName: 'Medium',
    colorName: 'COBALT BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026464',
    sizeName: 'Large',
    colorName: 'COBALT BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026471',
    sizeName: 'X Large',
    colorName: 'COBALT BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455544',
    sizeName: 'XXXS',
    colorName: 'FLOWER PETAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455551',
    sizeName: 'XX Small',
    colorName: 'FLOWER PETAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455568',
    sizeName: 'X Small',
    colorName: 'FLOWER PETAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455575',
    sizeName: 'Small',
    colorName: 'FLOWER PETAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455582',
    sizeName: 'Medium',
    colorName: 'FLOWER PETAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455599',
    sizeName: 'Large',
    colorName: 'FLOWER PETAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455605',
    sizeName: 'X Large',
    colorName: 'FLOWER PETAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455612',
    sizeName: 'XX Large',
    colorName: 'FLOWER PETAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455629',
    sizeName: 'XXX Large',
    colorName: 'FLOWER PETAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026150',
    sizeName: 'XX Small',
    colorName: 'CHIANTI',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026167',
    sizeName: 'X Small',
    colorName: 'CHIANTI',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026174',
    sizeName: 'Small',
    colorName: 'CHIANTI',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026181',
    sizeName: 'Medium',
    colorName: 'CHIANTI',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026198',
    sizeName: 'Large',
    colorName: 'CHIANTI',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026204',
    sizeName: 'X Large',
    colorName: 'CHIANTI',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430286',
    sizeName: 'XX Small',
    colorName: 'ENSIGN BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430293',
    sizeName: 'X Small',
    colorName: 'ENSIGN BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430309',
    sizeName: 'Small',
    colorName: 'ENSIGN BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430316',
    sizeName: 'Medium',
    colorName: 'ENSIGN BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430323',
    sizeName: 'Large',
    colorName: 'ENSIGN BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430330',
    sizeName: 'X Large',
    colorName: 'ENSIGN BLUE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026518',
    sizeName: 'XX Small',
    colorName: 'ENGINE RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026525',
    sizeName: 'X Small',
    colorName: 'ENGINE RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026532',
    sizeName: 'Small',
    colorName: 'ENGINE RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026549',
    sizeName: 'Medium',
    colorName: 'ENGINE RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026556',
    sizeName: 'Large',
    colorName: 'ENGINE RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11026563',
    sizeName: 'X Large',
    colorName: 'ENGINE RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13100889',
    sizeName: 'XX Small',
    colorName: 'DUSTY MOSS',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13100896',
    sizeName: 'X Small',
    colorName: 'DUSTY MOSS',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13100902',
    sizeName: 'Small',
    colorName: 'DUSTY MOSS',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13100919',
    sizeName: 'Medium',
    colorName: 'DUSTY MOSS',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13100926',
    sizeName: 'Large',
    colorName: 'DUSTY MOSS',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13100933',
    sizeName: 'X Large',
    colorName: 'DUSTY MOSS',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242090',
    sizeName: 'XXXS',
    colorName: 'PEONY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242106',
    sizeName: 'XX Small',
    colorName: 'PEONY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242113',
    sizeName: 'X Small',
    colorName: 'PEONY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242120',
    sizeName: 'Small',
    colorName: 'PEONY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242137',
    sizeName: 'Medium',
    colorName: 'PEONY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242144',
    sizeName: 'Large',
    colorName: 'PEONY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242151',
    sizeName: 'X Large',
    colorName: 'PEONY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242168',
    sizeName: 'XX Large',
    colorName: 'PEONY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242175',
    sizeName: 'XXX Large',
    colorName: 'PEONY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13081867',
    sizeName: 'XX Small',
    colorName: 'BRIGHT TAMALE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13081874',
    sizeName: 'X Small',
    colorName: 'BRIGHT TAMALE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13081881',
    sizeName: 'Small',
    colorName: 'BRIGHT TAMALE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13081898',
    sizeName: 'Medium',
    colorName: 'BRIGHT TAMALE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13081904',
    sizeName: 'Large',
    colorName: 'BRIGHT TAMALE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13081911',
    sizeName: 'X Large',
    colorName: 'BRIGHT TAMALE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12350292',
    sizeName: 'XX Small',
    colorName: 'MILITARY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12350308',
    sizeName: 'X Small',
    colorName: 'MILITARY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12350315',
    sizeName: 'Small',
    colorName: 'MILITARY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12350322',
    sizeName: 'Medium',
    colorName: 'MILITARY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12350339',
    sizeName: 'Large',
    colorName: 'MILITARY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12350346',
    sizeName: 'X Large',
    colorName: 'MILITARY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430552',
    sizeName: 'XX Small',
    colorName: 'IMPALA',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430569',
    sizeName: 'X Small',
    colorName: 'IMPALA',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430576',
    sizeName: 'Small',
    colorName: 'IMPALA',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430583',
    sizeName: 'Medium',
    colorName: 'IMPALA',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430590',
    sizeName: 'Large',
    colorName: 'IMPALA',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430606',
    sizeName: 'X Large',
    colorName: 'IMPALA',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430101',
    sizeName: 'XX Small',
    colorName: 'TRUE WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430118',
    sizeName: 'X Small',
    colorName: 'TRUE WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430125',
    sizeName: 'Small',
    colorName: 'TRUE WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430132',
    sizeName: 'Medium',
    colorName: 'TRUE WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430149',
    sizeName: 'Large',
    colorName: 'TRUE WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430156',
    sizeName: 'X Large',
    colorName: 'TRUE WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430194',
    sizeName: 'XX Small',
    colorName: 'PITCH BLACK',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430200',
    sizeName: 'X Small',
    colorName: 'PITCH BLACK',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430217',
    sizeName: 'Small',
    colorName: 'PITCH BLACK',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430224',
    sizeName: 'Medium',
    colorName: 'PITCH BLACK',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430231',
    sizeName: 'Large',
    colorName: 'PITCH BLACK',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430248',
    sizeName: 'X Large',
    colorName: 'PITCH BLACK',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430477',
    sizeName: 'X Small',
    colorName: 'RED LACQUER',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430484',
    sizeName: 'Small',
    colorName: 'RED LACQUER',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430507',
    sizeName: 'Large',
    colorName: 'RED LACQUER',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '10430514',
    sizeName: 'X Large',
    colorName: 'RED LACQUER',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12478316',
    sizeName: 'XX Small',
    colorName: 'ROSE BUD',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12478323',
    sizeName: 'X Small',
    colorName: 'ROSE BUD',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12478330',
    sizeName: 'Small',
    colorName: 'ROSE BUD',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12478347',
    sizeName: 'Medium',
    colorName: 'ROSE BUD',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12478354',
    sizeName: 'Large',
    colorName: 'ROSE BUD',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12478361',
    sizeName: 'X Large',
    colorName: 'ROSE BUD',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242182',
    sizeName: 'XXXS',
    colorName: 'NEUTRAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242199',
    sizeName: 'XX Small',
    colorName: 'NEUTRAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242205',
    sizeName: 'X Small',
    colorName: 'NEUTRAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242212',
    sizeName: 'Small',
    colorName: 'NEUTRAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242229',
    sizeName: 'Medium',
    colorName: 'NEUTRAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242236',
    sizeName: 'Large',
    colorName: 'NEUTRAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242243',
    sizeName: 'X Large',
    colorName: 'NEUTRAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242250',
    sizeName: 'XX Large',
    colorName: 'NEUTRAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14242267',
    sizeName: 'XXX Large',
    colorName: 'NEUTRAL',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455452',
    sizeName: 'XXXS',
    colorName: 'OLIVE GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455469',
    sizeName: 'XX Small',
    colorName: 'OLIVE GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455476',
    sizeName: 'X Small',
    colorName: 'OLIVE GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455483',
    sizeName: 'Small',
    colorName: 'OLIVE GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455490',
    sizeName: 'Medium',
    colorName: 'OLIVE GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455506',
    sizeName: 'Large',
    colorName: 'OLIVE GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455513',
    sizeName: 'X Large',
    colorName: 'OLIVE GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455520',
    sizeName: 'XX Large',
    colorName: 'OLIVE GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '14455537',
    sizeName: 'XXX Large',
    colorName: 'OLIVE GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
];

export default skus;
