const skus = [
  {
    skuId: '11979555',
    sizeName: 'X Small',
    colorName: 'GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979562',
    sizeName: 'Small',
    colorName: 'GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979579',
    sizeName: 'Medium',
    colorName: 'GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979586',
    sizeName: 'Large',
    colorName: 'GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979593',
    sizeName: 'X Large',
    colorName: 'GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979609',
    sizeName: 'XX Large',
    colorName: 'GREEN',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12261345',
    sizeName: 'M Tall',
    colorName: 'GREEN',
    sizeExtension1: 'M',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '12261352',
    sizeName: 'L Tall',
    colorName: 'GREEN',
    sizeExtension1: 'L',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '12261369',
    sizeName: 'XL Tall',
    colorName: 'GREEN',
    sizeExtension1: 'XL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '12261376',
    sizeName: 'XXL Tall',
    colorName: 'GREEN',
    sizeExtension1: 'XXL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13050924',
    sizeName: 'XXXS',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13050931',
    sizeName: 'XX Small',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13050948',
    sizeName: 'X Small',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13050955',
    sizeName: 'Small',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13050962',
    sizeName: 'Medium',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13050979',
    sizeName: 'Large',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13050986',
    sizeName: 'X Large',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13050993',
    sizeName: 'XX Large',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13051006',
    sizeName: 'XXX Large',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13051013',
    sizeName: 'XS Tall',
    colorName: 'NAVY',
    sizeExtension1: 'XS',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13051020',
    sizeName: 'S Tall',
    colorName: 'NAVY',
    sizeExtension1: 'S',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13051037',
    sizeName: 'M Tall',
    colorName: 'NAVY',
    sizeExtension1: 'M',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13051044',
    sizeName: 'L Tall',
    colorName: 'NAVY',
    sizeExtension1: 'L',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13051051',
    sizeName: 'XL Tall',
    colorName: 'NAVY',
    sizeExtension1: 'XL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13051068',
    sizeName: 'XXL Tall',
    colorName: 'NAVY',
    sizeExtension1: 'XXL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13051075',
    sizeName: 'XXXL TALL',
    colorName: 'NAVY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330125',
    sizeName: 'XXXS',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330132',
    sizeName: 'XX Small',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330149',
    sizeName: 'X Small',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330156',
    sizeName: 'Small',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330163',
    sizeName: 'Medium',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330170',
    sizeName: 'Large',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330187',
    sizeName: 'X Large',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330194',
    sizeName: 'XX Large',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330200',
    sizeName: 'XXX Large',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '13330217',
    sizeName: 'XS Tall',
    colorName: 'RUBY RED',
    sizeExtension1: 'XS',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13330224',
    sizeName: 'S Tall',
    colorName: 'RUBY RED',
    sizeExtension1: 'S',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13330231',
    sizeName: 'M Tall',
    colorName: 'RUBY RED',
    sizeExtension1: 'M',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13330248',
    sizeName: 'L Tall',
    colorName: 'RUBY RED',
    sizeExtension1: 'L',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13330255',
    sizeName: 'XL Tall',
    colorName: 'RUBY RED',
    sizeExtension1: 'XL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13330262',
    sizeName: 'XXL Tall',
    colorName: 'RUBY RED',
    sizeExtension1: 'XXL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '13330279',
    sizeName: 'XXXL TALL',
    colorName: 'RUBY RED',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11471202',
    sizeName: 'M Tall',
    colorName: 'BLACK',
    sizeExtension1: 'M',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '11471219',
    sizeName: 'L Tall',
    colorName: 'BLACK',
    sizeExtension1: 'L',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '11471226',
    sizeName: 'XL Tall',
    colorName: 'BLACK',
    sizeExtension1: 'XL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '11514107',
    sizeName: 'XXL Tall',
    colorName: 'BLACK',
    sizeExtension1: 'XXL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '11471028',
    sizeName: 'X Small',
    colorName: 'WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11471035',
    sizeName: 'Small',
    colorName: 'WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11471042',
    sizeName: 'Medium',
    colorName: 'WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11471059',
    sizeName: 'Large',
    colorName: 'WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11471066',
    sizeName: 'X Large',
    colorName: 'WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11512752',
    sizeName: 'XX Large',
    colorName: 'WHITE',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11471097',
    sizeName: 'M Tall',
    colorName: 'WHITE',
    sizeExtension1: 'M',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '11471103',
    sizeName: 'L Tall',
    colorName: 'WHITE',
    sizeExtension1: 'L',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '11471110',
    sizeName: 'XL Tall',
    colorName: 'WHITE',
    sizeExtension1: 'XL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '11514091',
    sizeName: 'XXL Tall',
    colorName: 'WHITE',
    sizeExtension1: 'XXL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '11979470',
    sizeName: 'X Small',
    colorName: 'GRAY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979487',
    sizeName: 'Small',
    colorName: 'GRAY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979494',
    sizeName: 'Medium',
    colorName: 'GRAY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979500',
    sizeName: 'Large',
    colorName: 'GRAY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979517',
    sizeName: 'X Large',
    colorName: 'GRAY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '11979524',
    sizeName: 'XX Large',
    colorName: 'GRAY',
    sizeExtension1: null,
    sizeExtension2: null,
  },
  {
    skuId: '12261284',
    sizeName: 'M Tall',
    colorName: 'GRAY',
    sizeExtension1: 'M',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '12261291',
    sizeName: 'L Tall',
    colorName: 'GRAY',
    sizeExtension1: 'L',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '12261307',
    sizeName: 'XL Tall',
    colorName: 'GRAY',
    sizeExtension1: 'XL',
    sizeExtension2: 'Tall',
  },
  {
    skuId: '12261314',
    sizeName: 'XXL Tall',
    colorName: 'GRAY',
    sizeExtension1: 'XXL',
    sizeExtension2: 'Tall',
  },
];

export default skus;
